package l1challenge.app.controllers;

import l1challenge.app.User;
import l1challenge.app.repositories.ArsWalletRepository;
import l1challenge.app.repositories.UserRepository;
import l1challenge.app.wallet.ArsWallet;
import l1challenge.app.wallet.Wallet;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.Optional;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;
    @Autowired
    private ArsWalletRepository arsWalletRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String name, @RequestParam String surname, @RequestParam String dni) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User(dni, name, surname);
        userRepository.save(n);
        arsWalletRepository.save(n.getArsWallet());
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path="/get")
    public @ResponseBody User getUserById(@RequestParam String dni) {
        // This returns a JSON or XML with the users
        User selectedUser = userRepository.findById(dni).get();
        ArsWallet userArsWallet = arsWalletRepository.findWalletByOwnerId(selectedUser.getDni());
        selectedUser.setArsWallet(userArsWallet);
        return selectedUser;
    }


}